Version 1.1.0

# The task

In this assignment you will need to implement features, based on nearest neighbours. 

KNN classifier (regressor) is a very powerful model, when the features are homogeneous and it is a very common practice to use KNN as first level model. In this homework we will extend KNN model and compute more features, based on nearest neighbors and their distances. 

You will need to implement a number of features, that were one of the key features, that leaded the instructors to prizes in [Otto](https://www.kaggle.com/c/otto-group-product-classification-challenge) and [Springleaf](https://www.kaggle.com/c/springleaf-marketing-response) competitions. Of course, the list of features you will need to implement can be extended, in fact in competitions the list was at least 3 times larger. So when solving a real competition do not hesitate to make up your own features.   

You can optionally implement multicore feature computation. Nearest neighbours are hard to compute so it is preferable to have a parallel version of the algorithm. In fact, it is really a cool skill to know how to use `multiprocessing`, `joblib` and etc. In this homework you will have a chance to see the benefits of parallel algorithm. 

# Check your versions

Some functions we use here are not present in old versions of the libraries, so make sure you have up-to-date software. 

In [3]:
import numpy as np
import pandas as pd 
import sklearn
import scipy.sparse 

for p in [np, pd, sklearn, scipy]:
    print (p.__name__, p.__version__)

numpy 1.15.4
pandas 0.24.2
sklearn 0.20.1
scipy 0.19.1


The versions should be not less than:

    numpy 1.13.1
    pandas 0.20.3
    sklearn 0.19.0
    scipy 0.19.1
   
**IMPORTANT!** The results with `scipy=1.0.0` will be different! Make sure you use _exactly_ version `0.19.1`.

# Load data

Learn features and labels. These features are actually OOF predictions of linear models.

In [4]:
train_path = '../readonly/KNN_features_data/X.npz'
train_labels = '../readonly/KNN_features_data/Y.npy'

test_path = '../readonly/KNN_features_data/X_test.npz'
test_labels = '../readonly/KNN_features_data/Y_test.npy'

# Train data
X = scipy.sparse.load_npz(train_path)
Y = np.load(train_labels)

# Test data
X_test = scipy.sparse.load_npz(test_path)
Y_test = np.load(test_labels)

# Out-of-fold features we loaded above were generated with n_splits=4 and skf seed 123
# So it is better to use seed 123 for generating KNN features as well 
skf_seed = 123
n_splits = 4

Below you need to implement features, based on nearest neighbors.

In [5]:
print(len(np.unique(Y)))
np.unique(Y)

29


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [6]:
x = np.array([5,5,5,5,5,4,2,5,5,5,4,3,3,1,5,7,6])

In [7]:
np.bincount(x)

array([0, 1, 1, 2, 2, 9, 1, 1])

In [8]:
np.where(x[1:] != x[:-1])

(array([ 4,  5,  6,  9, 10, 12, 13, 14, 15]),)

In [9]:
np.where(x[1:] > 400)

(array([], dtype=int64),)

In [10]:
np.where(x[1:] > 4)

(array([ 0,  1,  2,  3,  6,  7,  8, 13, 14, 15]),)

In [11]:
[np.where(x[1:] != x[:-1])[0][0] + 1]

[5]

In [12]:
x.tolist()

[5, 5, 5, 5, 5, 4, 2, 5, 5, 5, 4, 3, 3, 1, 5, 7, 6]

In [44]:
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.neighbors import NearestNeighbors
from multiprocessing import Pool

import numpy as np


class NearestNeighborsFeats(BaseEstimator, ClassifierMixin):
    '''
        This class should implement KNN features extraction 
    '''
    def __init__(self, n_jobs, k_list, metric, n_classes=None, n_neighbors=None, eps=1e-6):
        self.n_jobs = n_jobs
        self.k_list = k_list
        self.metric = metric
        
        if n_neighbors is None:
            self.n_neighbors = max(k_list) 
        else:
            self.n_neighbors = n_neighbors
            
        self.eps = eps        
        self.n_classes_ = n_classes
    
    def fit(self, X, y):
        '''
            Set's up the train set and self.NN object
        '''
        # Create a NearestNeighbors (NN) object. We will use it in `predict` function 
        self.NN = NearestNeighbors(n_neighbors=max(self.k_list), 
                                      metric=self.metric, 
                                      n_jobs=1, 
                                      algorithm='brute' if self.metric=='cosine' else 'auto')
        self.NN.fit(X)
        
        # Store labels 
        self.y_train = y
        
        # Save how many classes we have
        self.n_classes = np.unique(y).shape[0] if self.n_classes_ is None else self.n_classes_
        
        
    def predict(self, X):       
        '''
            Produces KNN features for every object of a dataset X
        '''
        if self.n_jobs == 1:
            test_feats = []
            for i in range(X.shape[0]):
                test_feats.append(self.get_features_for_one(X[i:i+1]))
        else:
            '''
                 *Make it parallel*
                     Number of threads should be controlled by `self.n_jobs`  
                     
                     
                     You can use whatever you want to do it
                     For Python 3 the simplest option would be to use 
                     `multiprocessing.Pool` (but don't use `multiprocessing.dummy.Pool` here)
                     You may try use `joblib` but you will most likely encounter an error, 
                     that you will need to google up (and eventually it will work slowly)
                     
                     For Python 2 I also suggest using `multiprocessing.Pool` 
                     You will need to use a hint from this blog 
                     http://qingkaikong.blogspot.ru/2016/12/python-parallel-method-in-class.html
                     I could not get `joblib` working at all for this code 
                     (but in general `joblib` is very convenient)
                     
            '''
            pool = Pool(self.n_jobs)
            test_feats = pool.map(self.get_features_for_one, X)
                
        return np.vstack(test_feats)
        
        
    def get_features_for_one(self, x):
        '''
            Computes KNN features for a single object `x`
        '''

        NN_output = self.NN.kneighbors(x)
        
        # Vector of size `n_neighbors`
        # Stores indices of the neighbors
        neighs = NN_output[1][0]
        
        # Vector of size `n_neighbors`
        # Stores distances to corresponding neighbors
        neighs_dist = NN_output[0][0] 

        # Vector of size `n_neighbors`
        # Stores labels of corresponding neighbors
        neighs_y = self.y_train[neighs] 
        
        ## ========================================== ##
        ##              YOUR CODE BELOW
        ## ========================================== ##
        
        # We will accumulate the computed features here
        # Eventually it will be a list of lists or np.arrays
        # and we will use np.hstack to concatenate those
        return_list = [] 
        
        
        ''' 
            1. Fraction of objects of every class.
               It is basically a KNNСlassifiers predictions.

               Take a look at `np.bincount` function, it can be very helpful
               Note that the values should sum up to one
        '''
        for k in self.k_list:
            feats = np.bincount(neighs_y[:k], minlength=self.n_classes) / k
            #feats = feats.tolist()
            #print('k={}  feats={} \n neighs_y[:k]={}'.format(k, feats, neighs_y[:k]))
            #print(sum(feats))
            
            assert len(feats) == self.n_classes
            return_list += [feats]
        
        
        '''
            2. Same label streak: the largest number N, 
               such that N nearest neighbors have the same label.
               
               What can help you: `np.where`
        '''
        if len(neighs_y) <= 1:
            feats = [len(neighs_y)]
        else:
            idxs = np.where(neighs_y[1:] != neighs_y[:-1])[0]
            if len(idxs) > 0:
                feats = [idxs[0] + 1]
            else:
                feats = [len(neighs_y)]
        
        assert len(feats) == 1
        return_list += [feats]
        
        '''
            3. Minimum distance to objects of each class
               Find the first instance of a class and take its distance as features.
               
               If there are no neighboring objects of some classes, 
               Then set distance to that class to be 999.

               `np.where` might be helpful
        '''
        feats = []
        for c in range(self.n_classes):
            idxs = np.where(neighs_y == c)[0]
            if len(idxs) > 0:
                feats.append(neighs_dist[idxs[0]])
            else:
                feats.append(999)
        
        assert len(feats) == self.n_classes
        return_list += [feats]
        
        '''
            4. Minimum *normalized* distance to objects of each class
               As 3. but we normalize (divide) the distances
               by the distance to the closest neighbor.
               
               If there are no neighboring objects of some classes, 
               Then set distance to that class to be 999.
               
               Do not forget to add self.eps to denominator.
        '''
        if len(neighs_dist) > 0:
            closest_dist = neighs_dist[0]
            feats = []
            for c in range(self.n_classes):
                idxs = np.where(neighs_y == c)[0]
                if len(idxs) > 0:
                    feats.append(neighs_dist[idxs[0]] / (closest_dist + self.eps))
                else:
                    feats.append(999)
        else:
            feats = [999] * self.n_classes
        
        assert len(feats) == self.n_classes
        return_list += [feats]
        
        '''
            5. 
               5.1 Distance to Kth neighbor
                   Think of this as of quantiles of a distribution
               5.2 Distance to Kth neighbor normalized by 
                   distance to the first neighbor
               
               feat_51, feat_52 are answers to 5.1. and 5.2.
               should be scalars
               
               Do not forget to add self.eps to denominator.
        '''
        for k in self.k_list:
            # I will assume that the dataset contains more elements than k
            feat_51 = neighs_dist[k-1]
            feat_52 = neighs_dist[k-1] / neighs_dist[0]
            
            return_list += [[feat_51, feat_52]]
        
        '''
            6. Mean distance to neighbors of each class for each K from `k_list` 
                   For each class select the neighbors of that class among K nearest neighbors 
                   and compute the average distance to those objects
                   
                   If there are no objects of a certain class among K neighbors, set mean distance to 999
                   
               You can use `np.bincount` with appropriate weights
               Don't forget, that if you divide by something, 
               You need to add `self.eps` to denominator.
        '''
        for k in self.k_list:
            
            feats = np.bincount(neighs_y[:k], weights=neighs_dist[:k], minlength=self.n_classes)
            feats = feats / (np.bincount(neighs_y, minlength=self.n_classes) + self.eps)
            feats = feats.tolist()
            
            assert len(feats) == self.n_classes
            return_list += [feats]
        
        
        # merge
        knn_feats = np.hstack(return_list)
        
        assert knn_feats.shape == (239,) or knn_feats.shape == (239, 1)
        return knn_feats

## Sanity check

To make sure you've implemented everything correctly we provide you the correct features for the first 50 objects.

In [45]:
# a list of K in KNN, starts with one 
k_list = [3, 8, 32]

# Load correct features
true_knn_feats_first50 = np.load('../readonly/KNN_features_data/knn_feats_test_first50.npy')

# Create instance of our KNN feature extractor
NNF = NearestNeighborsFeats(n_jobs=1, k_list=k_list, metric='minkowski')

# Fit on train set
NNF.fit(X, Y)

# Get features for test
test_knn_feats = NNF.predict(X_test[:50])

# This should be zero
print ('Deviation from ground thruth features: %f' % np.abs(test_knn_feats - true_knn_feats_first50[44:45]).sum())

deviation =np.abs(test_knn_feats - true_knn_feats_first50).sum(0)
for m in np.where(deviation > 1e-3)[0]: 
    p = np.where(np.array([87, 88, 117, 146, 152, 239]) > m)[0][0]
    print ('There is a problem in feature %d, which is a part of section %d.' % (m, p + 1))

/Users/antelinvestigacionydesarrollo/anaconda3/envs/competitiveds/lib/python3.6/site-packages/ipykernel_launcher.py:200: RuntimeWarning: divide by zero encountered in double_scalars


Deviation from ground thruth features: inf
There is a problem in feature 43, which is a part of section 1.
There is a problem in feature 44, which is a part of section 1.
There is a problem in feature 50, which is a part of section 1.
There is a problem in feature 51, which is a part of section 1.
There is a problem in feature 58, which is a part of section 1.
There is a problem in feature 59, which is a part of section 1.
There is a problem in feature 61, which is a part of section 1.
There is a problem in feature 62, which is a part of section 1.
There is a problem in feature 63, which is a part of section 1.
There is a problem in feature 64, which is a part of section 1.
There is a problem in feature 65, which is a part of section 1.
There is a problem in feature 66, which is a part of section 1.
There is a problem in feature 67, which is a part of section 1.
There is a problem in feature 68, which is a part of section 1.
There is a problem in feature 70, which is a part of section 

In [46]:
test_knn_feats.shape

(50, 239)

In [47]:
true_knn_feats_first50.shape

(50, 239)

In [34]:
problem1 = test_knn_feats[:, 43:87]
print(problem1.shape)
problem1

(50, 44)


array([[0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.     ],
       [0.     , 0.625  , 0.     , ..., 0.     , 0.03125, 0.     ],
       [0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.     ],
       ...,
       [0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.     ],
       [0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.03125],
       [0.     , 0.     , 0.     , ..., 0.     , 0.     , 0.     ]])

In [36]:
3 + 8 + 32

43

In [66]:
NNF.n_classes

29

In [67]:
NNF.n_classes * 3

87

In [60]:
diff = np.abs(test_knn_feats - true_knn_feats_first50)[:, 43]
diff.shape

(50,)

In [62]:
np.where(diff> 1e-3)

(array([44]),)

In [74]:
test_knn_feats[44,43]

0.125

In [75]:
43 - 29

14

In [77]:
test_knn_feats[44, 29:58]

array([0.25 , 0.   , 0.   , 0.   , 0.125, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.25 , 0.125, 0.125, 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.125, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   ])

In [78]:
true_knn_feats_first50[44,43]

0.25

In [79]:
true_knn_feats_first50[44,29:58]

array([0.25 , 0.   , 0.   , 0.   , 0.125, 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.   , 0.25 , 0.25 , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.125, 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   ])

Now implement parallel computations and compute features for the train and test sets. 

## Get features for test

Now compute features for the whole test set.

In [ ]:
for metric in ['minkowski', 'cosine']:
    print (metric)
    
    # Create instance of our KNN feature extractor
    NNF = NearestNeighborsFeats(n_jobs=4, k_list=k_list, metric=metric)
    
    # Fit on train set
    NNF.fit(X, Y)

    # Get features for test
    test_knn_feats = NNF.predict(X_test)
    
    # Dump the features to disk
    np.save('data/knn_feats_%s_test.npy' % metric , test_knn_feats)

## Get features for train

Compute features for train, using out-of-fold strategy.

In [ ]:
# Differently from other homework we will not implement OOF predictions ourselves
# but use sklearn's `cross_val_predict`
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import StratifiedKFold

# We will use two metrics for KNN
for metric in ['minkowski', 'cosine']:
    print (metric)
    
    # Set up splitting scheme, use StratifiedKFold
    # use skf_seed and n_splits defined above with shuffle=True
    skf = # YOUR CODE GOES HERE
    
    # Create instance of our KNN feature extractor
    # n_jobs can be larger than the number of cores
    NNF = NearestNeighborsFeats(n_jobs=4, k_list=k_list, metric=metric)
    
    # Get KNN features using OOF use cross_val_predict with right parameters
    preds = # YOUR CODE GOES HERE
    
    # Save the features
    np.save('data/knn_feats_%s_train.npy' % metric, preds)

# Submit

If you made the above cells work, just run the following cell to produce a number to submit.

In [ ]:
s = 0
for metric in ['minkowski', 'cosine']:
    knn_feats_train = np.load('data/knn_feats_%s_train.npy' % metric)
    knn_feats_test = np.load('data/knn_feats_%s_test.npy' % metric)
    
    s += knn_feats_train.mean() + knn_feats_test.mean()
    
answer = np.floor(s)
print (answer)

Submit!

In [ ]:
from grader import Grader

grader.submit_tag('statistic', answer)

STUDENT_EMAIL = # EMAIL HERE
STUDENT_TOKEN = # TOKEN HERE
grader.status()

grader.submit(STUDENT_EMAIL, STUDENT_TOKEN)